import streamlit as st

from core.model import ModelProvider

from common import about_from, cost_metric, load_example, page_tabs, selected_model

st.title("Reflexion")
st.caption("Generate → Critique → Revise: the agent reviews its own output before finalizing it.")

CORE_CONCEPT = """\
**What it is**

Reflexion is an iterative self-correction pattern that treats the model's own output as a draft
to be critiqued and refined, rather than trusting a single-shot response. It's most effective
where a first attempt is likely to be logically flawed, stylistically inconsistent, or
factually incomplete — a second pass catches what the first missed.

```mermaid
flowchart LR
    Task[User task] --> Writer["Writer agent — drafts freely, ignores constraints"]
    Writer --> Draft[Draft]
    Draft --> Critic["Critic agent — separate memory, finds gaps and inconsistencies"]
    Critic --> Critique[Critique]
    Draft --> Editor
    Critique --> Editor["Editor agent — synthesizes draft + critique"]
    Editor --> Final[Final output]
```

**Three separate personas, three separate memories**

- **Writer (drafting)** — generates the initial response, favoring a complete first attempt
  over technical constraints.
- **Critic (evaluation)** — a distinct agent instance with its own memory, so it isn't biased by
  having just written the draft. It looks for inconsistencies, tone issues, and logical gaps —
  without proposing the exact fix.
- **Editor (revision)** — takes the original draft *and* the critique and synthesizes the final,
  optimized version.

Keeping each persona on its own `Agent` instance (own memory, own system prompt) matters: a
model tasked with writing often can't see its own errors, while a dedicated critic persona,
unburdened by having produced the draft, is more likely to be objective and thorough — that
separation of concerns is the whole point of the pattern.

**How it differs from plain reasoning**

A single model call has no mechanism to step back and evaluate its own output before returning
it. Reflexion makes that evaluation step explicit and structured: the critique is a distinct
artifact, generated by a distinct pass, which the editor is then required to reconcile against
the original draft — rather than the model silently self-editing inside one continuous
generation.
"""


relpath = "examples/01_agent_patterns/03_reflexion.py"
mod = load_example(relpath)
tab_demo = page_tabs(relpath, mod, about_extra=about_from(CORE_CONCEPT))

with tab_demo:
    task = st.text_area("Task", value=mod.DEFAULT_TASK, height=80)

    if st.button("Run", type="primary"):
        provider = ModelProvider(selected_model())
        steps = list(mod.reflexion_steps(task, model_provider=provider))
        for i, (title, text) in enumerate(steps):
            if i > 0:
                st.divider()
            st.markdown(f"**{title}**")
            st.markdown(text)
        cost_metric(provider)
